### ISSUE TITLE
Cool Work

### ISSUE THREAD

**Issue by Brummi** [ruili3/Know-Your-Neighbors#1]
Just wanted to say great job on the paper! Cool to see an extension of BTS!

See you at CVPR!
Felix

**Comment by ruili3** [comment]
Hey Felix,

Thanks so much for your interest and for sharing the excellent [BTS codebase](https://github.com/Brummi/BehindTheScenes)! And many congrats on your newly accepted work "Cache me if you can", look forward to talking to you soon!

Best,
Rui
