### ISSUE TITLE
About the label of the scenes

### ISSUE THREAD

**Issue by River-Zhang** [ruili3/Know-Your-Neighbors#2]
Hi authors! Thanks for your great work!
I saw the outdoor_labels.txt in your repository and there are about 20 categories. I wonder how you get these labels. Did you use any models to process the dataset and predict the label or just write the label according to common sense? If I want to use it for indoor scenes, how can I set the labels? Thanks very much!

**Comment by ruili3** [comment]
Hi Zechuan,

Thanks for your interest in our work! We collect category names from the Cityscape semantic labels focusing on street views. 

We do not pre-process the dataset using other models but directly predict the labels using Lseg by computing cosine similarity between image and language embeddings. 

I am not that familiar with indoor scene datasets, but referring to indoor segmentation datasets to collect scene-specific label names is always a viable option, eg, NYU, ScanNet, etc. You can also extract labels from a wider range of categories from [ADE20K](https://huggingface.co/datasets/huggingface/label-files/blob/main/ade20k-id2label.json).

Hope this can help you :)

**Comment by River-Zhang** [comment]
Thanks for your reply! I'll try it!
